// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbB75yxdRJsLSAXni1ni7_2bNam3kqkW0',
    appId: '1:899915765545:android:6644a62f9509e6ba09c938',
    messagingSenderId: '899915765545',
    projectId: 'pilltodo-1c098',
    storageBucket: 'pilltodo-1c098.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKMK6OPSLryshkD232n155XhAsnnBxHHc',
    appId: '1:899915765545:ios:c470b7228a861f4b09c938',
    messagingSenderId: '899915765545',
    projectId: 'pilltodo-1c098',
    storageBucket: 'pilltodo-1c098.appspot.com',
    iosBundleId: 'com.example.pilltodo',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjXLaeMaLjxqRCl-A1DM2_wKyJerQQNmU',
    appId: '1:899915765545:web:8b770c35351205df09c938',
    messagingSenderId: '899915765545',
    projectId: 'pilltodo-1c098',
    authDomain: 'pilltodo-1c098.firebaseapp.com',
    storageBucket: 'pilltodo-1c098.appspot.com',
    measurementId: 'G-WZQ4W89E7K',
  );

}